### ISSUE TITLE
ORM框架可以加上mybatis

### ISSUE THREAD

**Issue by Myfanqie** [s4kibs4mi/java-developer-roadmap#12]
在中国，使用java的大部分的公司都是用的mybatis这个ORM框架

**Comment by SinnoSong** [comment]
@Myfanqie 他这个repo都放到github上了，意思是面向全世界的，而且在中日韩之外的地区ibatis(mybatis)是没有人用的。

**Comment by Myfanqie** [comment]
@SinnoSong 原来是这样吗，那我还是了解的少了

**Comment by SinnoSong** [comment]
@Myfanqie https://www.zhihu.com/question/309662829  看第一个回答就够了。mybatis现在就只有中国javaer多的地方会使用。你可以把这个issue关闭了。
