### ISSUE TITLE
The existence of pointer in java

### ISSUE THREAD

**Issue by Aragami1408** [s4kibs4mi/java-developer-roadmap#2]
![image](https://user-images.githubusercontent.com/25903678/70908754-99e1e180-203e-11ea-99cc-c8fb235e5428.png)

As you can see. Your map has the `Pointers` word which is redundant and pointers are impossible in java. You'd better read this for more information: [The Java Language Environment](https://www.oracle.com/technetwork/java/javase/simple-142616.html).

**Comment by s4kibs4mi** [comment]
@Aragami1408 thanks for issuing it. It basically means memory management.
