### ISSUE TITLE
The road map lacking more core skills for developer, especially in China.

### ISSUE THREAD

**Issue by oneWalker** [s4kibs4mi/java-developer-roadmap#4]
I just read the map originally and find it lack many fields, such as in the big data, which is not involved.
And the core part also lacking many things.  
For example, in the ORMS part, Mybatis is a core skill for the developers who can work in China. 
In the Framework part， Spring， SpringMVC，Springboot, Spring Cloud are independent, though it's based on the same principle.
In the testing part, JMeter is a more popular way than you have listed.
That's true for china's developers.
I am not sure whether it's correct for the developers outside China. You can consider adding it to your roadmap.

**Comment by s4kibs4mi** [comment]
@oneWalker feel free to contribute
