### ISSUE TITLE
Missing CI/CD

### ISSUE THREAD

**Issue by dammike** [s4kibs4mi/java-developer-roadmap#5]
Continuous integration and deployment can be identified with Dev-Ops, but that doesn't stop from there..
Increasing a large number of business now look for some sort of CI/CD skills with developers.

Jenkins for example can be included in the diagram.

**Comment by s4kibs4mi** [comment]
Hello @dammike feel free to contribute on this

**Comment by rishvantsingh** [comment]
Hii ..Should i write a demo jenkinsfile which can be included in the project and will help people to understand how the workflow is?

**Comment by s4kibs4mi** [comment]
@rishvantsingh sure why not.

**Comment by rishvantsingh** [comment]
Okkh ill do it.Please assign it to me.
